# Copyright (c) 2021 The WhiteBox Authors.  All rights reserved.
# Use of this source code is governed by a 3-Clause BSD license that can be
# found in the LICENSE file.
#
# Dependabot send alerts about outdated dependencies and known security
# vulnerabilites.

version: 2
updates:
  # Enable version updates for submodules.
  - package-ecosystem: "gitsubmodule"
    # Look for deps in the `/` directory.
    directory: "/"
    # Check for updates every day (weekdays).
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - dependencies