name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build-type: [Release, Debug, RelWithDebInfo]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/out -DCMAKE_BUILD_TYPE=${{matrix.buildType}}

    - name: Build
      run: cmake --build ${{github.workspace}}/out --config ${{matrix.buildType}}

    - name: Test
      working-directory: ${{github.workspace}}/out
      run: ctest -C ${{matrix.buildType}}

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build-type: [Release, Debug, RelWithDebInfo]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/out -DCMAKE_BUILD_TYPE=${{matrix.buildType}}

    - name: Build
      run: cmake --build ${{github.workspace}}/out --config ${{matrix.buildType}}

    - name: Test
      working-directory: ${{github.workspace}}/out
      run: ctest -C ${{matrix.buildType}}
      
  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build-type: [Release, Debug, RelWithDebInfo]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/out -DCMAKE_BUILD_TYPE=${{matrix.buildType}}

    - name: Build
      run: cmake --build ${{github.workspace}}/out --config ${{matrix.buildType}}

    - name: Test
      working-directory: ${{github.workspace}}/out
      run: ctest -C ${{matrix.buildType}}
