# Copyright (c) 2021 The WhiteBox Authors.  All rights reserved.
# Use of this source code is governed by a 3-Clause BSD license that can be
# found in the LICENSE file.

name: Build & Test

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'assets/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'assets/**'

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build: [ Release, Debug ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/out -Wdev -Werror=dev -DADD_FATAL_EXAMPLE=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCHANGE_G3LOG_DEBUG_TO_DBUG=ON -DDEBUG_BREAK_AT_FATAL_SIGNAL=ON -Dgtest_hide_internal_symbols=ON -DINSTALL_GTEST=OFF -DMI_BUILD_OBJECT=OFF -DMI_BUILD_STATIC=OFF -DMI_BUILD_TESTS=OFF -DMI_SECURE=ON -DWB_BUILD_TESTS=ON -DWB_MSVC_CXX_LANGUAGE_VERSION="c++latest"

      - name: Build on a ${{runner.os}}
        run: cmake --build ${{github.workspace}}/out --config ${{matrix.build}}

      - name: Test
        working-directory: ${{github.workspace}}/out
        run: ctest -C ${{matrix.build}}

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build: [ Release, Debug ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/out -Wdev -Werror=dev -DADD_FATAL_EXAMPLE=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCHANGE_G3LOG_DEBUG_TO_DBUG=ON -DDEBUG_BREAK_AT_FATAL_SIGNAL=ON -Dgtest_hide_internal_symbols=ON -DINSTALL_GTEST=OFF -DMI_BUILD_OBJECT=OFF -DMI_BUILD_STATIC=OFF -DMI_BUILD_TESTS=OFF -DMI_SECURE=ON -DWB_BUILD_TESTS=ON

      - name: Build on a ${{runner.os}}
        run: cmake --build ${{github.workspace}}/out --config ${{matrix.build}}

      - name: Test
        working-directory: ${{github.workspace}}/out
        run: ctest -C ${{matrix.build}}

  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build: [ Release, Debug ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/out -DADD_FATAL_EXAMPLE=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCHANGE_G3LOG_DEBUG_TO_DBUG=ON -DDEBUG_BREAK_AT_FATAL_SIGNAL=ON -Dgtest_hide_internal_symbols=ON -DINSTALL_GTEST=OFF -DMI_BUILD_OBJECT=OFF -DMI_BUILD_STATIC=OFF -DMI_BUILD_TESTS=OFF -DMI_SECURE=ON -DWB_BUILD_TESTS=ON

      - name: Build on a ${{runner.os}}
        run: cmake --build ${{github.workspace}}/out --config ${{matrix.build}}

      - name: Test
        working-directory: ${{github.workspace}}/out
        run: ctest -C ${{matrix.build}}
